/**
    Property of Transamerica and Aegon companies. Do not distribute without permission.
    Copyright (c) [2016] Transamerica Corporation, its affiliates and their licensors.
    Method which triggers the corresponding handler method for After Insert event.
    @author Samit Bhoumick
    @date  23/11/2016
    @description    This is wrapper which contains Response for Integration Utility.
*/

public class WFG_GenericResponseWrapper
{
    public Boolean boolIsError;
    public String strErrorCode;
    public String strErrorMessage;
    public String strResponseBody;
}